name: CI terraform VPC module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: run simple command
      run: whoami && pwd && ls -lha

    - name: run simple command
      run: terraform --version
